"""
QMIX — Monotonic Value Function Factorisation (Rashid et al., ICML 2018).

Standalone minimal implementation; provided as one of the SOTA baselines
referenced in the paper alongside MAPPO/HAPPO/HASAC.

Components
----------
- One shared agent Q-network (parameter sharing across agents). Input is
  agent observation, output is Q-value per action.
- A monotonic mixing network that combines per-agent Q-values into a
  joint Q-tot, conditioned on the global state. Mixing weights are
  produced by hyper-networks that are constrained to be non-negative
  (giving Q-tot the monotonicity property the paper proves is necessary
  for the IGM condition).
- Target networks for both, Polyak updated.
- Epsilon-greedy exploration that anneals from 1.0 to 0.05 over a
  configurable number of env steps.
- Replay buffer (we reuse our existing ``ReplayBuffer``).

This implementation is on the small side compared to the original (which
uses recurrent networks) — we use feedforward agents and a 32-unit mixer
to fit the single-thread runtime budget. Empirically still produces
QMIX-like learning curves on SMAC tasks.
"""

from __future__ import annotations

import copy
from typing import Any, Dict, List

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F


def _init_(m: nn.Module, gain=None) -> nn.Module:
    if isinstance(m, nn.Linear):
        if gain is None:
            gain = nn.init.calculate_gain('relu')
        nn.init.orthogonal_(m.weight, gain=gain)
        if m.bias is not None:
            nn.init.constant_(m.bias, 0.0)
    return m


class AgentQNet(nn.Module):
    """Per-agent (shared) Q-network: obs -> Q(s, a) for each action."""

    def __init__(self, obs_dim: int, n_actions: int, hidden: int = 64):
        super().__init__()
        self.fc1 = _init_(nn.Linear(obs_dim, hidden))
        self.fc2 = _init_(nn.Linear(hidden, hidden))
        self.head = _init_(nn.Linear(hidden, n_actions), gain=1.0)

    def forward(self, obs: torch.Tensor) -> torch.Tensor:
        h = F.relu(self.fc1(obs))
        h = F.relu(self.fc2(h))
        return self.head(h)


class QMixerNet(nn.Module):
    """Monotonic mixing network: (Q_1, ..., Q_N, state) -> Q_tot.

    The mixer is a 2-layer MLP with weights generated by hyper-networks
    from the global state. The hyper-net outputs are absoluted to enforce
    non-negativity, which gives Q_tot the IGM monotonicity property.
    """

    def __init__(self, n_agents: int, state_dim: int, embed_dim: int = 32):
        super().__init__()
        self.n_agents = n_agents
        self.embed_dim = embed_dim
        # Hyper-nets producing mixer layer weights from the state.
        self.hyper_w1 = nn.Linear(state_dim, embed_dim * n_agents)
        self.hyper_w2 = nn.Linear(state_dim, embed_dim)
        # Hyper-nets for biases.
        self.hyper_b1 = nn.Linear(state_dim, embed_dim)
        self.hyper_b2 = nn.Sequential(
            nn.Linear(state_dim, embed_dim),
            nn.ReLU(),
            nn.Linear(embed_dim, 1),
        )

    def forward(self, agent_qs: torch.Tensor, state: torch.Tensor) -> torch.Tensor:
        """agent_qs: (B, N), state: (B, state_dim) → Q_tot: (B, 1)."""
        B = agent_qs.shape[0]
        # First layer: |W1| has shape (B, N, embed); b1 has shape (B, 1, embed).
        w1 = torch.abs(self.hyper_w1(state)).view(B, self.n_agents, self.embed_dim)
        b1 = self.hyper_b1(state).view(B, 1, self.embed_dim)
        x = agent_qs.view(B, 1, self.n_agents)
        hidden = F.elu(torch.bmm(x, w1) + b1)                        # (B, 1, embed)
        # Second layer: |W2| has shape (B, embed, 1); b2 has shape (B, 1, 1).
        w2 = torch.abs(self.hyper_w2(state)).view(B, self.embed_dim, 1)
        b2 = self.hyper_b2(state).view(B, 1, 1)
        out = torch.bmm(hidden, w2) + b2                             # (B, 1, 1)
        return out.view(B, 1)


class QMIX:
    """QMIX joint-Q learning with monotonic value decomposition."""

    def __init__(
        self,
        args: Dict[str, Any],
        obs_dim: int,
        state_dim: int,
        action_dim: int,
        n_agents: int,
        device: torch.device | str = "cpu",
    ):
        self.args = args
        self.device = torch.device(device)
        self.n_agents = int(n_agents)
        self.n_actions = int(action_dim)

        self.agent_q = AgentQNet(obs_dim, action_dim).to(self.device)
        self.mixer = QMixerNet(n_agents, state_dim, embed_dim=32).to(self.device)
        self.target_agent_q = copy.deepcopy(self.agent_q)
        self.target_mixer = copy.deepcopy(self.mixer)
        for p in self.target_agent_q.parameters():
            p.requires_grad = False
        for p in self.target_mixer.parameters():
            p.requires_grad = False

        opt = args["optim"]
        qm = args["qmix"]

        self.optim = torch.optim.Adam(
            list(self.agent_q.parameters()) + list(self.mixer.parameters()),
            lr=opt["lr"],
        )
        self.gamma: float = float(qm["gamma"])
        self.tau: float = float(qm.get("tau", 0.005))
        self.batch_size: int = int(qm["batch_size"])
        # Epsilon-greedy schedule.
        self.eps_start: float = float(qm.get("eps_start", 1.0))
        self.eps_end: float = float(qm.get("eps_end", 0.05))
        self.eps_anneal_steps: int = int(qm.get("eps_anneal_steps", 50000))
        self._step_count = 0

    # ------------------------------------------------------------------ utils

    def _epsilon(self) -> float:
        frac = min(1.0, self._step_count / max(1, self.eps_anneal_steps))
        return self.eps_start + frac * (self.eps_end - self.eps_start)

    @torch.no_grad()
    def _polyak(self, src: nn.Module, tgt: nn.Module) -> None:
        for p_src, p_tgt in zip(src.parameters(), tgt.parameters()):
            p_tgt.data.mul_(1.0 - self.tau)
            p_tgt.data.add_(self.tau * p_src.data)

    # ---------------------------------------------------------- public API

    @torch.no_grad()
    def select_actions(
        self, obs: torch.Tensor, available_actions: torch.Tensor | None = None
    ):
        """Epsilon-greedy joint action."""
        squeeze = (obs.dim() == 2)
        if squeeze:
            obs = obs.unsqueeze(0)
            if available_actions is not None:
                available_actions = available_actions.unsqueeze(0)
        n_threads, N, O = obs.shape
        obs_flat = obs.reshape(n_threads * N, O)
        q = self.agent_q(obs_flat)                                # (n_threads*N, n_actions)
        q = q.view(n_threads, N, self.n_actions)
        if available_actions is not None:
            mask = ~available_actions.bool()
            q = q.masked_fill(mask, -1e10)
        eps = self._epsilon()
        # eps-greedy per (thread, agent).
        rand_actions = torch.randint(
            0, self.n_actions, (n_threads, N), device=self.device, dtype=torch.long
        )
        if available_actions is not None:
            # Sample uniformly among available actions for the random branch.
            avail = available_actions.bool().view(n_threads, N, self.n_actions).float()
            # Avoid div-by-zero by clamping; still picks a legal action when any available.
            rand_actions = torch.distributions.Categorical(probs=avail + 1e-8).sample()
        greedy_actions = q.argmax(dim=-1)
        rand = torch.rand(n_threads, N, device=self.device) < eps
        actions = torch.where(rand, rand_actions, greedy_actions)
        # Log-prob is unused for QMix but required by the runner contract.
        log_probs = torch.zeros(n_threads, N, device=self.device)
        self._step_count += n_threads
        if squeeze:
            actions = actions.squeeze(0)
            log_probs = log_probs.squeeze(0)
        return actions, log_probs

    def value(self, state: torch.Tensor) -> torch.Tensor:
        # Not used directly by QMix — stub for runner compatibility.
        return torch.zeros(state.shape[0], device=self.device)

    def set_groups(self, groups) -> None:
        return None

    def train(self, buffer) -> Dict[str, Any]:
        """One QMIX training step on a sampled batch from the replay buffer."""
        if len(buffer) < self.batch_size:
            return {"group_losses": {0: {"q_loss": float("nan")}},
                    "num_groups": 1, "active_groups": 1, "epsilon": self._epsilon()}

        batch = buffer.sample(self.batch_size)
        obs = batch["obs"]                                       # (B, N, O)
        next_obs = batch["next_obs"]                             # (B, N, O)
        state = batch["state"]                                   # (B, S)
        next_state = batch["next_state"]                         # (B, S)
        actions = batch["actions"].long().squeeze(-1)            # (B, N)
        rewards = batch["rewards"]                               # (B, 1)
        dones = batch["dones"]                                   # (B, 1)

        B, N, _ = obs.shape

        # Current Q for taken actions.
        q_all = self.agent_q(obs.reshape(B * N, -1)).view(B, N, self.n_actions)
        q_taken = q_all.gather(-1, actions.unsqueeze(-1)).squeeze(-1)    # (B, N)
        q_tot = self.mixer(q_taken, state)                                # (B, 1)

        # Target: r + gamma * (1 - done) * Q_tot_target(next_state, argmax)
        with torch.no_grad():
            q_next_all = self.target_agent_q(next_obs.reshape(B * N, -1)).view(B, N, self.n_actions)
            # Double-Q style: use online net to pick argmax, target net to evaluate.
            q_next_online = self.agent_q(next_obs.reshape(B * N, -1)).view(B, N, self.n_actions)
            argmax_a = q_next_online.argmax(dim=-1, keepdim=True)
            q_next_taken = q_next_all.gather(-1, argmax_a).squeeze(-1)   # (B, N)
            q_tot_next = self.target_mixer(q_next_taken, next_state)     # (B, 1)
            target = rewards + self.gamma * (1.0 - dones) * q_tot_next

        loss = F.mse_loss(q_tot, target)

        self.optim.zero_grad(set_to_none=True)
        loss.backward()
        nn.utils.clip_grad_norm_(
            list(self.agent_q.parameters()) + list(self.mixer.parameters()),
            10.0,
        )
        self.optim.step()

        # Polyak target update.
        self._polyak(self.agent_q, self.target_agent_q)
        self._polyak(self.mixer, self.target_mixer)

        return {
            "group_losses": {0: {
                "q_loss":    float(loss.detach()),
                "q_taken":   float(q_taken.mean().detach()),
                "q_target":  float(target.mean().detach()),
            }},
            "num_groups": 1,
            "active_groups": 1,
            "epsilon": self._epsilon(),
        }

    # ------------------------------------------------------------------
    # Checkpoint I/O
    # ------------------------------------------------------------------

    def state_dict(self) -> Dict:
        return {
            "agent_q":         self.agent_q.state_dict(),
            "mixer":           self.mixer.state_dict(),
            "target_agent_q":  self.target_agent_q.state_dict(),
            "target_mixer":    self.target_mixer.state_dict(),
            "step_count":      self._step_count,
        }

    def load_state_dict(self, sd: Dict) -> None:
        self.agent_q.load_state_dict(sd["agent_q"])
        self.mixer.load_state_dict(sd["mixer"])
        self.target_agent_q.load_state_dict(sd["target_agent_q"])
        self.target_mixer.load_state_dict(sd["target_mixer"])
        self._step_count = int(sd.get("step_count", 0))


__all__ = ["QMIX"]
